'use client'

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/N0Z21HnAW8v
 */
import { Card, CardContent, CardHeader } from "@/components/ui/card"
import { ChevronDownIcon, ChevronUpIcon } from '@radix-ui/react-icons';
import React, {useState} from 'react'

import { Button } from "@/components/ui/button"
import axios from 'axios'
import { useClientWebpage } from '@/contexts/ClientWebpageContext';

export default function TestBar() {
  const { pages, setPages } = useClientWebpage();
  const [isMinimized, setIsMinimized] = useState(true);

  const toggleMinimize = () => {
    setIsMinimized(!isMinimized);
  };


  const imageToText = async () => {
    console.log("hello")
    try {
      const response = await axios.post('http://localhost:3000/api/scripts');
  
      if (response.status === 200) {
        // Handle success
        console.log(response.data.result);
      } else {
        // Handle error
        console.error('Error executing script');
      }
      } catch (error) {
        console.error(`Error: ${error.message}`);
      }
  };

  const renameFrogFolders = async () => {
    try {
      const response = await fetch('/api/rename-frog-folders', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        // Send any necessary data
      });
  
      if (!response.ok) {
        throw new Error('Error processing files');
      }
  
      // Handle response data
      const result = await response.json();
      console.log(result);
    } catch (error) {
      console.error('Failed to process files:', error);
    }
  };

  // I'm gonna have to use a context provider
  const testCSVParse = async () => {
    try {
      const response = await fetch('/api/load-from-frog', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          dir: "unionknoxville",
          webpages: pages // Add the webpages array here
        })
      });
  
      if (!response.ok) {
        throw new Error('Error processing files');
      }
  
      // Handle response data
      const { result } = await response.json();

      // Assuming 'result' is the array of objects with the scraped data
      // Make sure to include the 'name' field when mapping over your data
      let mergedData = pages.map(page => {
        const matchingResult = result.find(r => r.url === page.url);
        return {
          ...matchingResult, // This spreads all properties from the matching result
          ...page,           // This spreads all properties from the page, potentially overwriting duplicates from result
          name: page.name    // Ensure the 'name' field is explicitly set from the page object
        };
      });

      setPages(mergedData);
      console.log(pages);
    } catch (error) {
      console.error('Failed to process files:', error);
    }
  };

  return (
    (
      <Card className="max-w-md mx-auto" style={{position: 'absolute', right: '0', bottom: '0'}}>
      <CardHeader>
        <div className="flex justify-between items-center w-full">
          <h3 className="text-sm font-semibold">Test Functions</h3>
          <Button onClick={toggleMinimize} variant="ghost">
            {isMinimized ? <ChevronUpIcon className="h-5 w-5" /> : <ChevronDownIcon className="h-5 w-5" />}
          </Button>
        </div>
      </CardHeader>
      {!isMinimized && (
        <CardContent className="flex flex-col items-center space-y-2">
          <Button onClick={imageToText} variant="outline">Read Image</Button>
          <Button onClick={renameFrogFolders} variant="outline">Rename Frog Folders</Button>
          <Button onClick={testCSVParse} variant="outline">Parse CSV</Button>
        </CardContent>
      )}
    </Card>)
  );
}
