'use client'

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/N0Z21HnAW8v
 */
import { Card, CardContent, CardHeader } from "@/components/ui/card"

import { Button } from "@/components/ui/button"
import axios from 'axios'

export default function TestBar() {

  const imageToText = async () => {
    console.log("hello")
    try {
      const response = await axios.post('http://localhost:3000/api/scripts');
  
      if (response.status === 200) {
        // Handle success
        console.log(response.data.result);
      } else {
        // Handle error
        console.error('Error executing script');
      }
      } catch (error) {
        console.error(`Error: ${error.message}`);
      }
  };

  return (
    (
      <Card className="max-w-md mx-auto" style={{position:'absolute',right:'0',bottom:'0'}}>
        <CardHeader>
          <h3 className="text-lg font-semibold">Test Functions</h3>
        </CardHeader>
        <CardContent className="flex flex-col items-center space-y-2">
          <Button onClick= {imageToText} className="" variant="outline">Read Image</Button>
        </CardContent>
      </Card>)
  );
}
